databases:
  - name: mylinkdb
    databaseName: mylink
    user: mylinkuser

services:
  - type: web
    name: mylink-press
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: mylinkdb
          property: connectionString